### ISSUE TITLE
White flicker when zooming out

### ISSUE THREAD

**Issue by codergautam** [Mario-Duarte/ImageZoom#10]
I am getting a white flicker when zooming out. It's not on your website, so maybe I am messing something up.

My code:

          <ImageZoom src={Image} alt='Pupil Not Detected' width={size} height={size} />

It's very basic, so not sure what is causing this. I am using it in an TypeScript Electron app with React

Video:

https://github.com/Mario-Duarte/react-image-zooom/assets/66850133/a18e1d2d-6e3b-4ab5-a863-a171b4e026e7

**Comment by Mario-Duarte** [comment]
That is quite interesting, I tried to replicate the issue but only managed to briefly (on first zoom out) replicate it when my network was throttled.

I have never tested this particular component with Electron, I would try to inspect the page and I would try to see if the src of the image is been unset or if you see any request for the same image in the network tab.

![Group 1](https://github.com/Mario-Duarte/react-image-zooom/assets/8998720/6863a305-50c4-4472-9228-13dd5f0f5464)

The weirdness comes around the fact that the zoomed-in image never changes opacity as that sits in the background of the `figure` container and the zoom part is activated by fading out and in the original image on top.

Hope that makes sense and helps you in the debug process.

**Comment by Mario-Duarte** [comment]
After a few new features I cannot replicate this, so I am closing this issue
