### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'nodeName')

### ISSUE THREAD

**Issue by wal-nagama** [Mario-Duarte/ImageZoom#2]
Facing this issue with internal dependency. Please help. Have already tried upgrading and downgrading node versions.

TypeError: Cannot read properties of undefined (reading 'nodeName')
setup
node_modules/js-image-zoom/js-image-zoom.js:186

 ```
 183 |     data.sourceImg.element = container.children[0];
  184 | 
  185 |     // if sourceImg is not an img (might be a picture element), try to find one
> 186 |     if (data.sourceImg.element.nodeName !== "IMG") {
  187 |         data.sourceImg.element = data.sourceImg.element.querySelector('img');
  188 |     }
  189 | }
```

**Comment by Mario-Duarte** [comment]
Thanks for bringing this to my attention, I will look into updating all dependencies.

**Comment by Mario-Duarte** [comment]
@wal-nagama could you please let me know the version of node you are currently using?

**Comment by primoz-k** [comment]
I am having the same issue. Node version: 20.16.0

EDIT: Yeah, this was due to the wrong package installed. I had `react-image-zoom` instead of `react-image-zooom`.
