### ISSUE TITLE
Zoom a div?

### ISSUE THREAD

**Issue by mledwards** [Mario-Duarte/ImageZoom#3]
Is it possible to zoom a div? I have an image with icons overlayed, and I'd love it if they moved at the same time.

**Comment by Mario-Duarte** [comment]
HI @mledwards, this was created and only tested to zoom on images. There is no guarantee that would work on div's but thank you for your suggestion and will take that into consideration on a future update or even a new hook/component.

**Comment by mledwards** [comment]
Ah, no worries. Incase it helps anyone, I tried `react-map-interaction`, which sort of does what I want. Needed to use `onTouchStart` for the items on top of the image to be tappable on mobile.
