### ISSUE TITLE
Detect when the image can't be loaded

### ISSUE THREAD

**Issue by cstffx** [Mario-Duarte/ImageZoom#5]
It could be useful have access to the onError event to catch situations when the image can't be loaded and then show an alternative content if needed.

**Comment by Mario-Duarte** [comment]
> It could be useful have access to the onError event to catch situations when the image can't be loaded and then show an alternative content if needed.

Thanks for the feedback, this may be something I will consider to add.

**Comment by Mario-Duarte** [comment]
> It could be useful have access to the onError event to catch situations when the image can't be loaded and then show an alternative content if needed.

This has now been implemented in the latest version -> https://github.com/Mario-Duarte/react-image-zooom/releases/tag/1.2.0
