### ISSUE TITLE
drag enlarged image in mobile

### ISSUE THREAD

**Issue by 020AlievIB** [Mario-Duarte/ImageZoom#6]
Allow in the mobile version to move image by dragging your finger over the image display area. 

Tap on the zoomed image returns to the original state of the image.

**Comment by Mario-Duarte** [comment]
> Allow in the mobile version to move image by dragging your finger over the image display area.
> 
> Tap on the zoomed image returns to the original state of the image.

THanks for the feedback and suggestions, I will consider to add this in an update.

**Comment by Mario-Duarte** [comment]
This is now WIP and should be released soon

**Comment by Mario-Duarte** [comment]
Implemented as of [version 1.3](https://github.com/Mario-Duarte/react-image-zooom/releases/tag/1.3.1)
