### ISSUE TITLE
Causes slide show to not move

### ISSUE THREAD

**Issue by Dionne-Stratton** [Mario-Duarte/ImageZoom#7]
I have what amounts to a slide show functionality that allows my users to click left or right to view the next or previous image in the gallery. After swapping <ImageZoom> for my <img>, the zoom works but the image doesn't change when hitting the left and right arrows, though all the rest of the data including the url updates. You can see how the slides should work here: https://serenityimages.studio/gallery/0

**Comment by Mario-Duarte** [comment]
I am sorry that you are having trouble with this, unfortunately without further details in regard to the issue I am unable to assist you. 
- What have you used for the slider? 
- What are the steps to reproduce this in code?
- can you create a codesandbox or codepen that replicates the issue?

Have you also tried other sliders like [Swiper](https://swiperjs.com/)?

**Comment by Dionne-Stratton** [comment]
I don't know what "slider" you mean, it's just vanilla JS inside a react app with basic useState at the app level. The page has an array of objects (an image and details for the art piece) It displays the correct image and other data based on it's place in the array. I'm using a standard img tag to display the image normally. All I did was swap it based on the directions for using your image zoom and with your component, the image is not updating with the rest of the data when I move it though the array. The data updates as it should, including the image data, but your component does not render the new image.

**Comment by Mario-Duarte** [comment]
I am not able to replicate the issue when updating the src of the image on `ImageZoom` using the `useState`, here is a demo of this -> https://codepen.io/MarioDesigns/pen/xxQzxYN/30174463be80e9e34f634463dd9701c9

If you would create a demo of the issue and share it with me I would be happy to help.
