### ISSUE TITLE
Permitir que la imagen cambie con une estado

### ISSUE THREAD

**Issue by ghost** [Mario-Duarte/ImageZoom#8]
Tengo un estado que cambia la imagen, pero no se logra apreciar el cambio

**Comment by Mario-Duarte** [comment]
> Tengo un estado que cambia la imagen, pero no se logra apreciar el cambio

Investigaré el problema y lanzaré una solución o te informaré de una solución.

**Comment by Mario-Duarte** [comment]
He intentado replicar el problema, pero no he tenido suerte y todo parece funcionar como debería. He creado una demostración donde cambio la fuente de la imagen del ImageZoom a través de un useState aquí -> https://codepen.io/MarioDesigns/pen/xxQzxYN/30174463be80e9e34f634463dd9701c9
